name: api_client
description: Firebase API client
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  app_core:
    path: ../app_core

  # Firebase
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.1.0

  # Flutter SDK
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^5.1.0
