name: rando
description: "create and share lists"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  api_client:
    path: packages/api_client
  app_core:
    path: packages/app_core
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.4
  board_repository:
    path: packages/board_repository
  dotenv: ^4.2.0
  equatable: ^2.0.5
  flow_builder: ^0.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.0.2
  intl: ^0.18.1
  post_repository:
    path: packages/post_repository
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  user_repository:
    path: packages/user_repository

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
